# Generated by Django 4.1.3 on 2022-11-28 01:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppFamiliares', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='familiares',
            old_name='cumpleaños',
            new_name='cumpleanos',
        ),
    ]
